swagger: '2.0'
host: www.cambridge.org
basePath: /engage/coe
schemes:
  - https
info:
  title: Cambridge Open Engage Public API Documentation
  version: 0.0.87
  description: |-
    Cambridge Open Engage is the early and open content platform from Cambridge University Press, providing the space and resources for researchers to connect, collaborate, and rapidly disseminate early and open research in various formats.
paths:
  /public-api/v1/items:
    get:
      summary: Search items
      operationId: getPublicapiV1Items
      description: |-
        Search for items passing search term and filters. In the QUERY PARAMETERS section you will find all parameters that you can add to query.
      parameters:
        - type: string
          default: ''
          name: term
          in: query
        - type: number
          default: 0
          name: skip
          in: query
        - type: number
          default: 10
          maximum: 50
          name: limit
          in: query
        - type: string
          default: PUBLISHED_DATE_DESC
          enum:
            - VIEWS_COUNT_ASC
            - VIEWS_COUNT_DESC
            - CITATION_COUNT_ASC
            - CITATION_COUNT_DESC
            - READ_COUNT_ASC
            - READ_COUNT_DESC
            - RELEVANT_ASC
            - RELEVANT_DESC
            - PUBLISHED_DATE_ASC
            - PUBLISHED_DATE_DESC
          name: sort
          in: query
        - type: string
          name: author
          in: query
        - type: string
          format: date
          description: >-
            Enter date in format of YYYY-MM-DD or in ISO format of
            YYYY-MM-DDThh:mm:ssZ
          name: searchDateFrom
          in: query
        - type: string
          format: date
          description: >-
            Enter date in format of YYYY-MM-DD or in ISO format of
            YYYY-MM-DDThh:mm:ssZ
          name: searchDateTo
          in: query
        - type: array
          x-constraint:
            single: true
          items:
            type: string
            x-constraint:
              length: 24
            x-format:
              hex:
                byteAligned: false
          collectionFormat: multi
          name: categoryIds
          in: query
        - type: array
          x-constraint:
            single: true
          items:
            type: string
            x-constraint:
              length: 24
            x-format:
              hex:
                byteAligned: false
          collectionFormat: multi
          name: subjectIds
          in: query
      tags:
        - public-api/v1/items
      responses:
        '200':
          schema:
            $ref: '#/definitions/Result'
          description: Success
        '400':
          description: Bad request
        '429':
          description: >-
            Too Many Requests, please throttle or talk to us if you think
            there's a problem
  /public-api/v1/oai:
    get:
      summary: Open Archives Initiative interface
      operationId: getPublicapiV1Oai
      description: >
        Fetch public articles metadata using Open Archives Initiative (OAI) protocol.
      parameters:
        - type: string
          enum:
            - GetRecord
            - Identify
            - ListIdentifiers
            - ListMetadataFormats
            - ListRecords
          name: verb
          in: query
        - type: string
          name: identifier
          in: query
        - type: string
          enum:
            - oai_dc
          name: metadataPrefix
          in: query
        - type: string
          format: date
          description: >-
            Enter date in format of YYYY-MM-DD or in ISO format of
            YYYY-MM-DDThh:mm:ssZ
          name: from
          in: query
        - type: string
          format: date
          description: >-
            Enter date in format of YYYY-MM-DD or in ISO format of
            YYYY-MM-DDThh:mm:ssZ
          name: until
          in: query
        - type: string
          name: resumptionToken
          in: query
      tags:
        - public-api/v1/oai
      responses:
        '400':
          description: Bad request
        '429':
          description: >-
            Too Many Requests, please throttle or talk to us if you think
            there's a problem
  /public-api/v1/subjects:
    get:
      summary: Get all subjects with metadata
      operationId: getPublicapiV1Subjects
      description: |-
        Endpoint to get all available subjects with total number of subjects and subject metadata such as name, id, description and number of published preprints in the subject.
      tags:
        - public-api/v1/subjects
      responses:
        '200':
          schema:
            $ref: '#/definitions/Model16'
          description: Success
        '400':
          description: Bad request
        '429':
          description: >-
            Too Many Requests, please throttle or talk to us if you think
            there's a problem
  /public-api/v1/items/{itemId}:
    get:
      summary: Get item metadata
      operationId: getPublicapiV1ItemsItemid
      description: |-
        View the metadata for an item by passing its unique item id.
      parameters:
        - type: string
          x-constraint:
            length: 24
          x-format:
            hex:
              byteAligned: false
          name: itemId
          in: path
          required: true
      tags:
        - public-api/v1/items
      responses:
        '200':
          schema:
            $ref: '#/definitions/Model21'
          description: Success
        '400':
          description: Bad request
        '410':
          description: Item has been withdrawn
        '429':
          description: >-
            Too Many Requests, please throttle or talk to us if you think
            there's a problem
  /public-api/v1/items/doi/{doi*2}:
    get:
      summary: Get item metadata based on item's doi
      operationId: getPublicapiV1ItemsDoiDoi2
      description: |-
        View the metadata for an item by passing its doi.
      parameters:
        - type: string
          name: doi*2
          in: path
          required: true
      tags:
        - public-api/v1/items
      responses:
        '200':
          schema:
            $ref: '#/definitions/Model21'
          description: Success
        '400':
          description: Bad request
        '410':
          description: Item has been withdrawn
        '429':
          description: >-
            Too Many Requests, please throttle or talk to us if you think
            there's a problem
definitions:
  vor:
    type: object
    properties:
      vorDoi:
        type: string
      url:
        type: string
  contentType:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      name:
        type: string
  Model1:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      name:
        type: string
      description:
        type: string
  categories:
    type: array
    items:
      $ref: '#/definitions/Model1'
  smallThumbnail:
    type: object
    properties:
      url:
        type: string
  bannerAsset:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      mimeType:
        type: string
      fileName:
        type: string
      fileSizeBytes:
        type: number
      smallThumbnail:
        $ref: '#/definitions/smallThumbnail'
      mediumThumbnail:
        $ref: '#/definitions/smallThumbnail'
      largeThumbnail:
        $ref: '#/definitions/smallThumbnail'
      original:
        $ref: '#/definitions/smallThumbnail'
  Model2:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      url:
        type: string
        x-format:
          uri: true
      text:
        type: string
      asset:
        $ref: '#/definitions/bannerAsset'
  sponsors:
    type: array
    items:
      $ref: '#/definitions/Model2'
  event:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      eventGroup:
        $ref: '#/definitions/contentType'
      title:
        type: string
      description:
        type: string
      location:
        type: string
      startDate:
        type: string
        x-format:
          isoDate: true
      endDate:
        type: string
        x-format:
          isoDate: true
      createdAt:
        type: string
        x-format:
          isoDate: true
      updatedAt:
        type: string
        x-format:
          isoDate: true
      bannerAsset:
        $ref: '#/definitions/bannerAsset'
      sponsors:
        $ref: '#/definitions/sponsors'
      url:
        type: string
        x-format:
          uri: true
      status:
        type: string
  Model3:
    type: object
    properties:
      funderId:
        type: string
      name:
        type: string
      grantNumber:
        type: string
      url:
        type: string
        x-format:
          uri: true
      title:
        type: string
  funders:
    type: array
    items:
      $ref: '#/definitions/Model3'
  Model4:
    type: object
    properties:
      name:
        type: string
      country:
        type: string
      rorId:
        type: string
  institutions:
    type: array
    items:
      $ref: '#/definitions/Model4'
  Model5:
    type: object
    properties:
      orcid:
        type: string
      title:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      institutions:
        $ref: '#/definitions/institutions'
  authors:
    type: array
    items:
      $ref: '#/definitions/Model5'
  Model6:
    type: object
    properties:
      description:
        type: string
      value:
        type: number
  metrics:
    type: array
    items:
      $ref: '#/definitions/Model6'
  Model7:
    type: object
    properties:
      version:
        type: string
        example: '1'
      itemId:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      legacyId:
        type: string
  versionRefs:
    type: array
    minItems: 1
    items:
      $ref: '#/definitions/Model7'
  keywords:
    type: array
    items:
      type: string
  Model8:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      title:
        type: string
      description:
        type: string
      asset:
        $ref: '#/definitions/bannerAsset'
  suppItems:
    type: array
    items:
      $ref: '#/definitions/Model8'
  license:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      name:
        type: string
      description:
        type: string
      url:
        type: string
        x-format:
          uri: true
  Model9:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      url:
        type: string
        x-format:
          uri: true
  webLinks:
    type: array
    items:
      $ref: '#/definitions/Model9'
  author:
    type: object
    properties:
      title:
        type: string
      firstName:
        type: string
      lastName:
        type: string
  Model10:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      author:
        $ref: '#/definitions/author'
      createdAt:
        type: string
        x-format:
          isoDate: true
      number:
        type: number
      content:
        type: string
      status:
        type: string
  replies:
    type: array
    items:
      $ref: '#/definitions/Model10'
  Model11:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      author:
        $ref: '#/definitions/author'
      createdAt:
        type: string
        x-format:
          isoDate: true
      number:
        type: number
      content:
        type: string
      status:
        type: string
      replies:
        $ref: '#/definitions/replies'
  latestComments:
    type: array
    items:
      $ref: '#/definitions/Model11'
  itemDetailsResponseSchema:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      doi:
        type: string
      vor:
        $ref: '#/definitions/vor'
      title:
        type: string
      abstract:
        type: string
      contentType:
        $ref: '#/definitions/contentType'
      categories:
        $ref: '#/definitions/categories'
      subject:
        $ref: '#/definitions/Model1'
      event:
        $ref: '#/definitions/event'
      status:
        type: string
        enum:
          - PUBLISHED
          - RETRACTING
          - RETRACTED
      statusDate:
        type: string
        x-format:
          isoDate: true
      funders:
        $ref: '#/definitions/funders'
      authors:
        $ref: '#/definitions/authors'
      metrics:
        $ref: '#/definitions/metrics'
      version:
        type: string
        example: '1'
      versionRefs:
        $ref: '#/definitions/versionRefs'
      submittedDate:
        type: string
        x-format:
          isoDate: true
      publishedDate:
        type: string
        x-format:
          isoDate: true
      approvedDate:
        type: string
        x-format:
          isoDate: true
      keywords:
        $ref: '#/definitions/keywords'
      hasCompetingInterests:
        type: boolean
      competingInterestsDeclaration:
        type: string
      gainedEthicsApproval:
        type: string
        enum:
          - 'YES'
          - NOT_RELEVANT
      suppItems:
        $ref: '#/definitions/suppItems'
      asset:
        $ref: '#/definitions/bannerAsset'
      license:
        $ref: '#/definitions/license'
      webLinks:
        $ref: '#/definitions/webLinks'
      origin:
        type: string
      termsAcceptance:
        type: boolean
      versionNote:
        type: string
      latestComments:
        $ref: '#/definitions/latestComments'
      commentsCount:
        type: number
      isLatestVersion:
        type: boolean
    required:
      - title
  Model12:
    type: object
    properties:
      itemDetailsResponseSchema:
        $ref: '#/definitions/itemDetailsResponseSchema'
  itemHits:
    type: array
    items:
      $ref: '#/definitions/Model12'
  Result:
    type: object
    properties:
      totalCount:
        type: number
      itemHits:
        $ref: '#/definitions/itemHits'
  licenseSchema:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      name:
        type: string
      description:
        type: string
      label:
        type: string
      tooltip:
        type: string
      url:
        type: string
        x-format:
          uri: true
    required:
      - name
  Model13:
    type: object
    properties:
      licenseSchema:
        $ref: '#/definitions/licenseSchema'
  licenses:
    type: array
    items:
      $ref: '#/definitions/Model13'
  subjectsSchema:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24 
        x-format:
          hex:
            byteAligned: false
      name:
        type: string
      description:
        type: string
      count:
        type: number
    required:
      - name
  Model15:
    type: object
    properties:
      subjectsSchema:
        $ref: '#/definitions/subjectsSchema'
  subjects:
    type: array
    items:
      $ref: '#/definitions/Model15'
  Model16:
    type: object
    properties:
      totalCount:
        type: number
      subjects:
        $ref: '#/definitions/subjects'
  Model18:
    type: object
    properties:
      orcid:
        type: string
      title:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      institutions:
        $ref: '#/definitions/institutions'
      displayOrder:
        type: number
  Model19:
    type: array
    items:
      $ref: '#/definitions/Model18'
  Model20:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      name:
        type: string
      label:
        type: string
      description:
        type: string
      tooltip:
        type: string
      url:
        type: string
        x-format:
          uri: true
  contentWithdrawal:
    type: object
    properties:
      isWithdrawn:
        type: boolean
  Model21:
    type: object
    properties:
      id:
        type: string
        x-constraint:
          length: 24
        x-format:
          hex:
            byteAligned: false
      doi:
        type: string
      vor:
        $ref: '#/definitions/vor'
      title:
        type: string
      abstract:
        type: string
      contentType:
        $ref: '#/definitions/contentType'
      categories:
        $ref: '#/definitions/categories'
      subject:
        $ref: '#/definitions/Model1'
      event:
        $ref: '#/definitions/event'
      status:
        type: string
        enum:
          - PUBLISHED
          - RETRACTING
          - RETRACTED
      statusDate:
        type: string
        x-format:
          isoDate: true
      funders:
        $ref: '#/definitions/funders'
      authors:
        $ref: '#/definitions/Model19'
      metrics:
        $ref: '#/definitions/metrics'
      version:
        type: string
        example: '1'
      versionRefs:
        $ref: '#/definitions/versionRefs'
      submittedDate:
        type: string
        x-format:
          isoDate: true
      publishedDate:
        type: string
        x-format:
          isoDate: true
      approvedDate:
        type: string
        x-format:
          isoDate: true
      keywords:
        $ref: '#/definitions/keywords'
      hasCompetingInterests:
        type: boolean
      competingInterestsDeclaration:
        type: string
      gainedEthicsApproval:
        type: string
        enum:
          - 'YES'
          - NOT_RELEVANT
      suppItems:
        $ref: '#/definitions/suppItems'
      asset:
        $ref: '#/definitions/bannerAsset'
      license:
        $ref: '#/definitions/Model20'
      webLinks:
        $ref: '#/definitions/webLinks'
      origin:
        type: string
      termsAcceptance:
        type: boolean
      versionNote:
        type: string
      latestComments:
        $ref: '#/definitions/latestComments'
      commentsCount:
        type: number
      isLatestVersion:
        type: boolean
      contentWithdrawal:
        $ref: '#/definitions/contentWithdrawal'
      legacyId:
        type: string
    required:
      - title
