openapi: 3.0.3
info:
  title: Passwordinator - OpenAPI 3.0
  description: |-
    Passwordinator is an API that lets you generate random passwords of varying complexity in your app/website. The api is free and can be accessed at any origin.
  version: 1.0.0
servers:
  - url: https://passwordinator.onrender.com
paths:
  /:
    get:
      summary: Random password
      description: Generate customized random password 
      operationId: generatePass
      parameters:
        - name: len
          in: query
          description: length of passward, minimum 7, default 12
          schema:
            type: integer
        - name: num
          in: query
          description: whether to include numbers in the password
          schema:
            type: boolean
        - name: char
          in: query
          description: whether to include special characters in the password
          schema:
            type: boolean
        - name: caps
          in: query
          description: whether to include upper case letters in the password
          schema:
            type: boolean
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
