openapi: 3.0.0
info:
  title: UK Sustainability API
  description: |-
    The UK Sustainability API offers a predictive overview of the regional carbon intensity of Great Britain's (GB) electrical system, extending up to two days ahead of real-time. This API grants timely and programmatic access to both projected and assessed carbon intensity information. The Carbon Intensity forecast specifically covers CO2 emissions associated with electricity production. This encompasses emissions from all major metered power plants, imported energy via interconnectors, transmission and distribution losses, and takes into account national electricity consumption, as well as embedded wind and solar power generation.
    The from parameter specifies the starting datetime for a given operation or query in ISO8601 format, which includes the year (YYYY), month (MM), day (DD), hour (hh), minute (mm), and timezone offset (Z) from UTC time.
    
  contact:
    name: National Grid
    email: alasdair.bruce@nationalgrid.com
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  version: 2.0.0
externalDocs:
  description: Find out more about UK Sustainability API
  url: https://carbonintensity.org.uk/
servers:
  - url: https://api.carbonintensity.org.uk
tags:
  - name: intensity
    description: Carbon Intensity - National
  - name: stats
    description: Statistics - National
paths:
  /intensity:
    get:
      operationId: getIntensityNow
      tags:
        - intensity
      summary: Get Carbon Intensity data for current half hour.
      description: Retrieves Carbon Intensity data for the current half hour. All times provided in UTC (+00:00).
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/date:
    get:
      operationId: getIntensityToday
      tags:
        - intensity
      summary: Get Carbon Intensity data for today.
      description: Get Carbon Intensity data for today. All times provided in UTC (+00:00).
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Intensity"
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: "500 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /intensity/date/{date}:
    get:
      operationId: getIntensityDate
      tags:
        - intensity
      summary: Get Carbon Intensity data for a specific date.
      description: Get Carbon Intensity data for a specific date. All times provided in UTC (+00:00).
      parameters:
        - name: date
          in: path
          description: Date in YYYY-MM-DD format.
          required: true
          schema:
            type: string
            example: 2023-01-25
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        '400':
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/date/{date}/{period}:
    get:
      operationId: getIntensityDatePeriod
      tags:
        - intensity
      summary: Get Carbon Intensity data for specific date and period.
      description: Get Carbon Intensity data for a specific date and half hour settlement period. All times provided in UTC (+00:00).
      parameters:
        - name: date
          in: path
          required: true
          description: Date in YYYY-MM-DD format.
          schema:
            type: string
            example: 2023-01-25
        - name: period
          in: path
          required: true
          description: Half hour settlement period between 1-48.
          schema:
            type: string
            example: "42"
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/factors:
    get:
      operationId: getIntensityFactors
      tags:
        - intensity
      summary: Get Carbon Intensity factors for each fuel type.
      description: Get Carbon Intensity factors for each fuel type.
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/{from}:
    get:
      operationId: getIntensityFrom
      tags:
        - intensity
      summary: Get Carbon Intensity data for specific half hour period.
      description: Returns carbon intensity data for a specific half hour period. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          required: true
          schema:
            type: string
            example: 2023-01-25T12:35Z
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/{from}/fw24h:
    get:
      operationId: getIntensityFw24h
      tags:
        - intensity
      summary: Get Carbon Intensity data 24hrs forwards from specific datetime.
      description: Get Carbon Intensity data between the {from} datetime specified and 24hrs after. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          required: true
          schema:
            type: string
            example: 2023-01-25T12:35Z
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/{from}/fw48h:
    get:
      operationId: getIntensityFw48h
      tags:
        - intensity
      summary: Get Carbon Intensity data 48hrs forwards from specific datetime.
      description: Get Carbon Intensity data between the {from} datetime specified and 48hrs after. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          required: true
          schema:
            type: string
            example: 2023-01-25T12:35Z
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/{from}/pt24h:
    get:
      operationId: getIntensityPt24h
      tags:
        - intensity
      summary: Get Carbon Intensity data 24hrs in the past of a specific datetime.
      description: Get Carbon Intensity data between the {from} datetime specified and 24hrs before. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          required: true
          schema:
            type: string
            example: 2023-01-25T12:35Z
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/{from}/{to}:
    get:
      operationId: getIntensityFromTo
      tags:
        - intensity
      summary: Get Carbon Intensity data between from and to datetime
      description: Get Carbon Intensity data between the {from} and {to} datetimes. The maximum date range is limited to 14 days. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          required: true
          schema:
            type: string
            example: 2023-01-25T12:35Z
        - name: to
          in: path
          description: End datetime in in ISO8601 format YYYY-MM-DDThh:mmZ
          required: true
          schema:
            type: string
            example: 2023-01-26T12:35Z
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/stats/{from}/{to}:
    get:
      operationId: getIntensityStats
      tags:
        - stats
      summary: Get Carbon Intensity statistics
      description: Get Carbon Intensity statistics (average, max, mean) between from and to datetime. The maximum date range is limited to 30 days. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          required: true
          schema:
            type: string
            example: 2023-01-25T12:35Z
        - name: to
          in: path
          required: true
          description: End datetime in ISO8601 format YYYY-MM-DDThh:mmZ.
          schema:
            type: string
            example: 2023-01-26T12:35Z
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statistics'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Intensity:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              from:
                type: string
                format: date-time
              to:
                type: string
                format: date-time
              intensity:
                type: object
                properties:
                  forecast:
                    type: number
                  actual:
                    type: number
                  index:
                    type: string
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
    Statistics:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              from:
                type: string
                format: date-time
              to:
                type: string
                format: date-time
              intensity:
                type: object
                properties:
                  max:
                    type: number
                  average:
                    type: number
                  min:
                    type: number
                  index:
                    type: string
